#version 450
// GLSL Point Cloud triangulation
// TODO

// Splitts the 320 x 420 screen into 4 sections.
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D img1;
layout(set = 0, binding = 1) uniform sampler2D img2;

layout(set = 0, binding = 2, rgba8) uniform writeonly image2D depth; // Not the final output type. This is just so it builds

void main() {
    vec4 to_write = vec4(0, 0, 0, 0); // for now
    imageStore(depth, ivec2(gl_GlobalInvocationID.xy), to_write);
}